var express = require("express")
var app = express()

var login = require("./login")
app.use(login)
var product = require("./product")
app.use(product)
var supplier = require("./supplier")
app.use(supplier)
var purchase = require("./purchase")
app.use(purchase)
var customer = require("./customer")
app.use(customer)
var type = require("./type")
app.use(type)
var sale = require("./sale")
app.use(sale)
var stock = require("./stock")
app.use(stock)
var charts = require("./charts")
app.use(charts)
var chat = require("./chat")
app.use(chat)
var upload = require("./uploadimg")
app.use(upload)
var user = require("./user")
app.use(user)

module.exports = app